---
version: "3"
silent: true

tasks:
  pre-commit:init:
    desc: Initiate and install dependencies
    cmds:
      - pre-commit install
  pre-commit:run:
    desc: Run all pre-commit hooks
    cmds:
      - pre-commit run -a

  cargo:check:
    cmd: cargo check

  cargo:deny:
    cmd: cargo deny check all

  cargo:clippy:
    cmd: cargo clippy

  docker:build:
    cmds:
      - |
          docker buildx build . \
          --platform=linux/amd64,linux/arm64 \
          --tag rustic-exporter:local
      - |
          docker buildx build . \
          --tag rustic-exporter:local \
          --load
