---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true

tasks:
  pre-commit:init:
    desc: Initiate and install dependencies
    cmds:
      - pre-commit install
  pre-commit:run:
    desc: Run all pre-commit hooks
    cmds:
      - pre-commit run -a

  cargo:check:
    cmd: cargo check

  cargo:deny:
    cmd: cargo deny check all

  cargo:clippy:
    cmd: cargo clippy

  cargo:build:release:
    cmd: cargo build -r

  format:
    cmd: dprint fmt

  test:prepare:
    cmd: uv sync

  test:
    deps: [test:prepare]
    cmd: uv run --frozen pytest {{.CLI_ARGS}}

  test:functional:
    deps: [test:prepare]
    cmd: uv run --frozen pytest tests/functional -n auto {{.CLI_ARGS}}

  docker:build:
    cmds:
      - |
          docker buildx build . \
          --platform=linux/amd64,linux/arm64 \
          --tag rustic-exporter:local
      - |
          docker buildx build . \
          --tag rustic-exporter:local \
          --load
